# Generated by Django 3.2.15 on 2022-09-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('CPic', models.ImageField(default='', upload_to='static/category/')),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=70)),
                ('pid', models.IntegerField()),
                ('cdate', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='morder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=70)),
                ('pid', models.IntegerField()),
                ('remarks', models.CharField(max_length=20)),
                ('odate', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='myproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pprice', models.FloatField()),
                ('dprice', models.FloatField()),
                ('psize', models.CharField(max_length=20)),
                ('pcolor', models.CharField(max_length=20)),
                ('pdes', models.TextField()),
                ('pdel', models.CharField(max_length=50)),
                ('ppic', models.ImageField(default='', upload_to='static/product/')),
                ('pdate', models.DateTimeField()),
                ('pcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
