# Generated by Django 3.2.15 on 2022-09-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220905_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='uregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('userpic', models.ImageField(upload_to='')),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
