# Generated by Django 3.2.15 on 2022-09-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_uregister_userpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='uregister',
            name='passwd',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
