# Generated by Django 3.2.15 on 2022-09-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_mcart_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='odate',
            field=models.CharField(max_length=30),
        ),
    ]
