# Generated by Django 3.2.15 on 2022-09-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_morder_odate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincate',
            name='picture',
            field=models.ImageField(upload_to='static/mcategory/'),
        ),
        migrations.AlterField(
            model_name='uregister',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
