# Generated by Django 3.2.15 on 2022-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220911_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uregister',
            name='id',
        ),
        migrations.AlterField(
            model_name='uregister',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
